// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM1jb0vsKuR_BpmwMjBEjQD6vYxt-adXk',
    appId: '1:531344421124:web:1e9aaced94ff7a8f60e051',
    messagingSenderId: '531344421124',
    projectId: 'e-commerce-f62e1',
    authDomain: 'e-commerce-f62e1.firebaseapp.com',
    storageBucket: 'e-commerce-f62e1.appspot.com',
    measurementId: 'G-C669L9T0X1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwUAC5k_1bLqXIeQPbKT8o6llQ7KyBVE4',
    appId: '1:531344421124:android:00efef129179823860e051',
    messagingSenderId: '531344421124',
    projectId: 'e-commerce-f62e1',
    storageBucket: 'e-commerce-f62e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJgj6xOgqGQ4-KuXSqey9ohWJ1EPbNtdY',
    appId: '1:531344421124:ios:84c3a693775852ab60e051',
    messagingSenderId: '531344421124',
    projectId: 'e-commerce-f62e1',
    storageBucket: 'e-commerce-f62e1.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJgj6xOgqGQ4-KuXSqey9ohWJ1EPbNtdY',
    appId: '1:531344421124:ios:84c3a693775852ab60e051',
    messagingSenderId: '531344421124',
    projectId: 'e-commerce-f62e1',
    storageBucket: 'e-commerce-f62e1.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM1jb0vsKuR_BpmwMjBEjQD6vYxt-adXk',
    appId: '1:531344421124:web:7fdf0ff59d05f30960e051',
    messagingSenderId: '531344421124',
    projectId: 'e-commerce-f62e1',
    authDomain: 'e-commerce-f62e1.firebaseapp.com',
    storageBucket: 'e-commerce-f62e1.appspot.com',
    measurementId: 'G-M7PV3JCYEC',
  );
}
